services:
  ecom-discovery-service:
    build: ./discovery-service
    container_name: ecom-discovery-service
    ports:
      - "8761:8761"
    expose:
      - "8761"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 10s
      retries: 4
  ecom-config-service:
    build: ./config-service
    container_name: ecom-config-service
    ports:
      - "9999:9999"
    expose:
      - '9999'
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9999/actuator/health" ]
      interval: 10s
      retries: 4
    environment:
      - DISCOVERY_SERVICE_URL:http://ecom-discovery-service:8761/eureka
    depends_on:
      ecom-discovery-service:
          condition: service_healthy
  ecom-customer-service:
    build: ./customer-service
    container_name: ecom-customer-service
    ports:
      - "8081:8081"
    expose:
      - '8081'
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8081/actuator/health" ]
      interval: 10s
      retries: 4
    environment:
      - DISCOVERY_SERVICE_URL:http://ecom-discovery-service:8761/eureka
      - CONFIG_SERVICE_URL=http://ecom-config-service:9999
    depends_on:
      ecom-config-service:
        condition: service_healthy
  ecom-inventory-service:
    build: ./inventory-service
    container_name: ecom-inventory-service
    ports:
      - "8082:8082"
    expose:
      - '8082'
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8082/actuator/health" ]
      interval: 10s
      retries: 4
    environment:
      - DISCOVERY_SERVICE_URL:http://ecom-discovery-service:8761/eureka
      - CONFIG_SERVICEURL=http://ecom-config-service:9999
    depends_on:
      ecom-config-service:
        condition: service_healthy
  ecom-gateway-service:
    build: ./gateway-service
    container_name: ecom-gateway-service
    ports:
      - "8888:8888"
    expose:
      - '8888'
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8888/actuator/health" ]
      interval: 10s
      retries: 4
    environment:
      - DISCOVERY_SERVICE_URL:http://ecom-discovery-service:8761/eureka
      - CONFIG_SERVICEURL=http://ecom-config-service:9999
    depends_on:
      ecom-customer-service:
        condition: service_healthy
      ecom-inventory-service:
        condition: service_healthy
  ecom-billing-service:
    build: ./billing-service
    container_name: ecom-billing-service
    ports:
      - "8083:8083"
    expose:
      - '8083'
    environment:
      - DISCOVERY_SERVICE_URL:http://ecom-discovery-service:8761/eureka
      - CONFIG_SERVICEURL=http://ecom-config-service:9999
    depends_on:
      ecom-gateway-service:
        condition: service_healthy