apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: ecom-billing-service
  name: ecom-billing-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ecom-billing-service
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: ecom-billing-service
    spec:
      containers:
        - env:
            - name: CONFIG_SERVICEURL
              value: http://ecom-config-service:9999
          image: ecom-billing-service
          name: ecom-billing-service
          ports:
            - containerPort: 8083
              protocol: TCP
      restartPolicy: Always
