apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: ecom-config-service
  name: ecom-config-service
spec:
  ports:
    - name: "9999"
      port: 9999
      targetPort: 9999
    - name: 9999-tcp
      port: 9999
      targetPort: 9999
  selector:
    io.kompose.service: ecom-config-service
