apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: ecom-discovery-service
  name: ecom-discovery-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ecom-discovery-service
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: ecom-discovery-service
    spec:
      containers:
        - image: ecom-discovery-service
          livenessProbe:
            exec:
              command:
                - curl
                - -f
                - http://localhost:8761/actuator/health
            failureThreshold: 4
            periodSeconds: 10
          name: ecom-discovery-service
          ports:
            - containerPort: 8761
              protocol: TCP
      restartPolicy: Always
