apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: ecom-discovery-service
  name: ecom-discovery-service
spec:
  ports:
    - name: "8761"
      port: 8761
      targetPort: 8761
    - name: 8761-tcp
      port: 8761
      targetPort: 8761
  selector:
    io.kompose.service: ecom-discovery-service
