apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: ecom-inventory-service
  name: ecom-inventory-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ecom-inventory-service
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: ecom-inventory-service
    spec:
      containers:
        - env:
            - name: CONFIG_SERVICEURL
              value: http://ecom-config-service:9999
          image: ecom-inventory-service
          livenessProbe:
            exec:
              command:
                - curl
                - -f
                - http://localhost:8082/actuator/health
            failureThreshold: 4
            periodSeconds: 10
          name: ecom-inventory-service
          ports:
            - containerPort: 8082
              protocol: TCP
      restartPolicy: Always
